### ISSUE TITLE
Styled Components dependency needs updating to v6

### ISSUE THREAD

**Issue by lloydh** [sanity-io/color-input#61]
The main Sanity package recently added support for Styled Components v6, however this package still specifies ^5.2 creating a dependency conflict.

**Comment by Ashwin-op** [comment]
@lloydh you can use this https://www.npmjs.com/package/@ashwin-op/color-input if you need it temporarily. I am using it for another project and it seems to work

**Comment by lloydh** [comment]
@snorrees any chance you could take a look at bumping this dep?
